// FLIGHTS
export const FETCH_FLIGHTS = "FETCH_FLIGHTS";
export const FETCH_BY_SEARCH = "FETCH_BY_SEARCH";
export const FETCH_SINGLE_FLIGHT = "FETCH_SINGLE_FLIGHT";

// HOTELS

export const FETCH_BY_SEARCH_HOTEL = "FETCH_BY_SEARCH_HOTEL";
export const FETCH_BY_HOTEL_ID = "FETCH_BY_HOTEL_ID";

// AUTH

export const AUTH = "AUTH";
export const AUTH_USER = "AUTH_USER";
export const LOGOUT = 'LOGOUT'
export const AUTH_CREATE = "AUTH_CREATE";
export const AUTH_BOOKING_UPDATE = "AUTH_BOOKING_UPDATE";
export const AUTH_HOTEL_BOOKING_UPDATE = "AUTH_HOTEL_BOOKING_UPDATE"
export const DELETEACCOUNT = "DELETEACCOUNT";